### ISSUE TITLE
Theme Request: East Asian

### ISSUE THREAD

**Issue by Armandeus66** [tianevitt/tianzes-landing-page#1]
I am running the PF2E adventure path Fists of the Ruby Phoenix, which is similar to a Kung Fu movie in style. Would you be interested in creating such a theme? Thanks!

**Comment by tianevitt** [comment]
Theme added. Thanks for the idea!

**Comment by Armandeus66** [comment]
Thank you!
I made a post about your module on the Fists of the Ruby Phoenix AP discussion within the Pathfinder on Foundry Discord server. I hope more people see your great work.
https://discord.com/channels/880968862240239708/891395280828768266/1289691695176487037
